apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myapp.fullname" . }}-mysql
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
stringData:
  db_driver: "com.mysql.cj.jdbc.Driver"
  db_url: "DB_URL"
  db_username: "DB_USERNAME"
  db_password: "DB_PASSWORD"